name: 'Preview Environments'
description: 'Deploy a Uffizzi Preview Environment for every pull request'
author: 'Adam Vollrath'
branding:
  color: 'yellow'
  icon: 'upload-cloud'
inputs:
  compose-file:
    description: 'An alternate compose file'
    required: false
    default: 'docker-compose.yaml'
  server:
    description: 'URL to Uffizzi'
    required: true
    default: 'https://app.uffizzi.com'
  username:
    description: 'Uffizzi username'
    required: false
  password:
    description: 'Uffizzi password'
    required: false
  project:
    description: 'Uffizzi project slug'
    required: false
  ghcr-username:
    description: 'Username to authenticate to GHCR'
    required: false
  ghcr-access-token:
    description: 'Password to authenticate to GHCR'
    required: false
  github-event-number:
    description: 'Value of `github.event.number` context'
    required: false
  github-ref:
    description: 'Value of `github.ref` context'
    required: false
  github-repository: 'Value of `github.repository` context'
    description: 'Value of `github.repository` context'
    required: false
  request-token:
    descrption: 'A token to access the pipeline information'
    required: false
  request-token-url:
    descrption: 'A url where the pipeline information can be accessed'
    required: false
  dockerhub-username:
    descrption: 'DockerHub username'
    required: false
  dockerhub-password:
    descrption: 'DockerHub password'
    required: false
outputs:
  url:
    description: 'URL where preview was deployed, if successful'
  id:
    description: 'ID of preview for later reference'
  containers_uri:
    description: 'URI to the deployment details'
runs:
  using: 'docker'
  image: 'docker://uffizzi/cli:v1'
  args:
    - 'preview'
    - 'create'
    - '--output=github-action'
    - '--set-labels="github.ref=${{ inputs.github-ref }} github.repository=${{ inputs.github-repository }} github.event.number=${{ inputs.github-event-number }}"'
    - ${{ inputs.compose-file }}
  env:
    UFFIZZI_PASSWORD: ${{ inputs.password }}
    UFFIZZI_SERVER: ${{ inputs.server }}
    UFFIZZI_USER: ${{ inputs.username }}
    UFFIZZI_PROJECT: ${{ inputs.project }}
    GITHUB_USERNAME: ${{ inputs.ghcr-username }}
    GITHUB_ACCESS_TOKEN: ${{ inputs.ghcr-access-token }}
    REQUEST_TOKEN: ${{ inputs.request-token}}
    REQUEST_TOKEN_URL: ${{ inputs.request-token-url }}
    DOCKERHUB_USERNAME: ${{ inputs.dockerhub-username }}
    DOCKERHUB_PASSWORD: ${{ inputs.dockerhub-password}}
